language : python
before_install:
- chmod +x manage.py
python:
- "3.6"
install: "pip install -r requirements.txt"
script:
- SECRET_KEY="something" ./manage.py test
- nosetests -v --with-coverage --cover-tests --cover-package=noseselecttests accounts/test_accounts_views.py
after_success:
    - bash <(curl -s https://codecov.io/bash)